<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Clover Diff for <?php echo $full_path; ?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="<?php echo $path_to_root; ?>.assets/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?php echo $path_to_root; ?>.assets/css/style.css" rel="stylesheet">
        <!--[if lt IE 9]>
        <script src="<?php echo $path_to_root; ?>.assets/js/html5shiv.min.js"></script>
        <script src="<?php echo $path_to_root; ?>.assets/js/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <header>
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <ol class="breadcrumb"><?php
                            echo $breadcrumbs;
                        ?></ol>
                    </div>
                </div>
            </div>
        </header>
        <div class="container">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <td>&nbsp;</td>
                    <td colspan="9"><div align="center"><strong>Code Coverage</strong></div></td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td colspan="3"><div align="center"><strong>Older Version Coverage</strong></div></td>
                    <td colspan="3"><div align="center"><strong>Newer Version Coverage</strong></div></td>
                    <td colspan="3"><div align="center"><strong>Coverage Difference</strong></div></td>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($items as $item): ?>
                    <?php echo $this->render("directory_item.html", $item); ?>
                <?php endforeach; ?>
                </tbody>
            </table>
            <footer>
                <hr/>
                <h4>Legend</h4>
                <p>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Coverage</th>
                                <th>Coverage Difference</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <div><span class="danger"><strong>Low</strong>: 0% to <?php echo $low_upper_bound; ?>%</span></div>
                                    <div><span class="warning"><strong>Medium</strong>: <?php echo $low_upper_bound; ?>% to <?php echo $high_lower_bound; ?>%</span></div>
                                    <div><span class="success"><strong>High</strong>: <?php echo $high_lower_bound; ?>% to 100%</span></div>
                                </td>
                                <td>
                                    <div><span class="danger"><strong>Critical</strong>: -100% to <?php echo $diff_lo_upper_level; ?>%</span></div>
                                    <div><span class="warning"><strong>Acceptable</strong>: <?php echo $diff_lo_upper_level; ?>% to <?php echo $diff_hi_lower_level; ?>%</span></div>
                                    <div><span class="success"><strong>Good</strong>: <?php echo $diff_hi_lower_level; ?>% to 100%</span></div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </p>
                <p>
                    <small>Generated by <a href="http://github.com/gergelyrozsas/clover-diff" target="_top">Clover Diff - <?php echo $version; ?></a> at <?php echo $date; ?>.</small>
                </p>
            </footer>
        </div>
        <script src="<?php echo $path_to_root; ?>.assets/js/jquery.min.js" type="text/javascript"></script>
        <script src="<?php echo $path_to_root; ?>.assets/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="<?php echo $path_to_root; ?>.assets/js/holder.min.js" type="text/javascript"></script>
    </body>
</html>
